site_name: Compiladores | Grupo 1

repo_name: "compiladores-equipe-1"
repo_url: https://github.com/brunna-martins/compiladores-equipe-1

nav:
  - Início: index.md
  - Acompanhamento Semanal:
    - Semana 1: acompanhamento/semana-01.md
    - Semana 2: acompanhamento/semana-02.md
  - Reuniões: 
    - Sprint 2:
      - Ata: reunioes/sprint2/ata.md
      - Pautas: reunioes/sprint2/pautas.md
    - Sprint 3:
      - Ata: reunioes/sprint3/ata.md
      - Pautas: reunioes/sprint3/pautas.md 
  - Entregas: 
    - Entrega 1:
      - Definição do Projeto: entrega1/definicao.md
      - Linguagem Escolhida: entrega1/linguagem.md
      - Cronograma de Sprints: entrega1/cronograma.md 
      - Decisões Técnicas: entrega1/decisoes.md
      - Desafios Encontrados: entrega1/desafios.md
      - Soluções Adotadas: entrega1/solucoes.md
  - Analisador Léxico: analisadores/analisador-lexico.md
  - Analisador Sintático: analisadores/analisador-sintatico.md
  - Analisador Semântico: analisadores/analisador-semantico.md
  - Tokens e comentários: tokens-comentarios.md
theme:
  name: material
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

  palette:
    - scheme: default
      primary: ''
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        
    - scheme: slate
      primary: ''
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  highlightjs: true

