name: Issue
description: Task técnica detalhada com objetivo, implementação, testes e documentação.
title: "🛠️ <Título da Task>"
labels: ["task", "enhancement"]
projects: ["brunna-martins/1"]
body:
  - type: textarea
    id: objetivo
    attributes:
      label: 🎯 Objetivo da issue
      description: Qual a finalidade desta task? O que ela resolve, habilita ou contribui para o projeto?
      placeholder: |
        Exemplo:
        - Reconhecer e tratar novas construções sintáticas no parser.
        - Implementar estrutura de controle condicional no compilador.
    validations:
      required: true

  - type: textarea
    id: implementar
    attributes:
      label: ⚙️ Implementar
      description: Quais passos ou modificações devem ser feitas para realizar essa task?
      value: |
        - [ ] Modificar arquivo X
        - [ ] Criar estrutura Y
        - [ ] Atualizar regra no parser
      placeholder: Liste os passos de implementação aqui.
    validations:
      required: true

  - type: textarea
    id: testar
    attributes:
      label: 🧪 Testar
      description: Quais casos de teste devem ser verificados ou criados? Como garantir que a task está funcionando?
      value: |
        - [ ] Criar arquivo de teste com input válido
        - [ ] Verificar falhas em casos inválidos
        - [ ] Garantir cobertura de casos alternativos
      placeholder: Liste os testes necessários aqui.
    validations:
      required: true

  - type: textarea
    id: documentar
    attributes:
      label: 📚 Documentar
      description: Há algo que precisa ser registrado? Código, decisões, links úteis, anotações?
      placeholder: |
        - Adicionar comentários no código
        - Registrar mudanças no README ou Wiki
        - Link para documentação externa
